version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
