version: 2
updates:
  - package-ecosystem: "pip"
    directory: "images/python-arcgis"
    groups:
      python-packages:
        patterns:
          - "*"
    commit-message:
      prefix: "fix"
      prefix-development: "fix"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "fix"
      prefix-development: "fix"
    schedule:
      interval: "weekly"
