apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: base-images
spec:
  images:
  - glob: "quay.io/geonet/**"
  - glob: "ghcr.io/geonet/**"
  authorities:
  - keyless:
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: "^(https://github.com/GeoNet/base-images/.github/workflows/(build|sync).yml@refs/(heads/main|tags/v[0-9].[0-9].[0-9]))$"
