on:
  push:
permissions:
  contents: read
  packages: write
jobs:
  run_delete_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "{{ secrets.github_token }}"
    steps:
      - name: Every time
        run: 'gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/geonet/packages/container/base-images%2Fcentos/versions/105779325'
