name: presubmit image exists
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  presubmit-image-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: GeoNet/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # main
      - name: resolve image to digest
        run: |
          jq '.sync[].source' -r -c <<< "$(yq e . -o json config.yaml)" | xargs -n 1 -I % -P 1000 crane digest %
